Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/jammy64"
config.vm.hostname = "ops"
config.vm.provider "virtualbox" do |vb|
vb.memory = "2048"
vb.cpus = 2
# Agregar disco adicional de 2GB para ejercicios de LVM
unless File.exist?('./disk_ops.vdi')
vb.customize ['createhd', '--filename', './disk_ops.vdi', '--size',
2048]
end
vb.customize ['storageattach', :id, '--storagectl', 'SCSI',
'--port', 2, '--device', 0, '--type', 'hdd', '--medium', './disk_ops.vdi']
end
config.vm.network "public_network"
config.vm.provision "shell", inline: <<-SHELL

apt-get update
apt-get install -y git lvm2

add-apt-repository ppa:zhangsongcui3371/fastfetch -y
apt-get update
apt-get install -y fastfetch


apt-get install -y ca-certificates curl gnupg
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
  https://download.docker.com/linux/ubuntu jammy stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

usermod -aG docker vagrant
systemctl enable docker
systemctl start docker
SHELL
end

